const USER = require("../models/user");
const {setUser} = require("../services/auth");

async function handleUserLogin(req, res) {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ message: "Please fill in all fields" });

    const user = await USER.findOne({ email });

    if (!user) return res.status(401).render("login", {
        message: "Invalid email or password",
    })

    const token = setUser(user);
    res.cookie("token", token)
    return res.redirect("/")

}

async function handleUsersignup(req, res) {
    const { name, email, password } = req.body;
    if (!name || !email || !password) return res.status(400).json({ message: "Please fill in all fields" });

    const existingUser = await USER.findOne({ email: email })

    if (existingUser) {
        return res.json({
            message: "User already exists",
        })
    }

    // The new user which is to be created will have all the below properties and a _uid which is generated by db.
    await USER.create({
        name,
        email,
        password
    })

    return res.redirect("/");

}

module.exports = { handleUserLogin, handleUsersignup }